### ISSUE TITLE
GNOME: App doesn't seem like it's in its own window

### ISSUE THREAD

**Issue by rany2** [refi64/flextop#6]
![image](https://user-images.githubusercontent.com/71077389/112478302-87e00a00-8d7c-11eb-968b-24641dd46d5d.png)

It says it's an Ungoogled Chromium window instead of Element

**Comment by rany2** [comment]
The problem is caused because of Wayland and it happens on Google Chrome as well. Closing …

**Comment by refi64** [comment]
Side note: this was indeed a Flextop issue, was fixed in 9f66dac84388f520ecab5ac4fa60df6343b7db5b.
